### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by starchild92** [edy1192/revestimientosjyg#1]
La barra de navegación necesito tu opinion: claro o obscura
los items de la barra alineados a la izquierda o derecha?

**Comment by edy1192** [comment]
Tendría que verla para decidir si clara u obscura y deberían ir alineados a la izquierda creo :P

**Comment by starchild92** [comment]
Te mando la imagen por WA o la vez luego?

**Comment by edy1192** [comment]
Luego, no tengo muchos megas. Cuándo llegue actualizo y la veo :)

Edilianny Sánchez
